packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': 9.39.2
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': 8.50.1
  '@typescript-eslint/parser': 8.50.1
  eslint: 9.39.2
  firebase: ^12.6.0
  globals: 15.15.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript-eslint: 8.50.1
