name: Lint

on:
  pull_request:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

jobs:
  lint:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint
