name: Pull request workflow
run-name: Test, lint, and preview branch ${{ github.head_ref }}

on: pull_request

env:
  PROJECT_ID: bytes-and-nibbles
  

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/set_up_env.yml

      - name: Test code
        run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/set_up_env.yml

      - name: Lint code
        run: npm run lint
  
  build_and_preview:
    name: Build and preview
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: ./.github/workflows/set_up_env.yml

      - name: Build
        run: npm run build

      - name: Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BYTES_AND_NIBBLES }}"
          projectId: ${{ env.PROJECT_ID }}
